#!/bin/bash

downloadPath="$HOME/Videos/downloaded"

help() {
	echo "Video Downloader - Scripted by thebluedragon"
	echo "usage:	ydv <args>"
}


getPath() {
	if [ -z $1 ]; then
		echo "$downloadPath/"
	else
		echo "$downloadPath/$1/"
	fi
}


if [ -z $1 ];then
	help
else
	read -p "[+] save to ($downloadPath): " input
	finalPath="$(getPath $input)"
	yt-dlp --format mp4 -o "$finalPath%(title)s.%(ext)s" $@
fi
